### ISSUE TITLE
MongoDB 查询报错  Can't compile a NewExpression with a constructor declared on an abstract class

### ISSUE THREAD

**Issue by zhuxian** [egametang/ET#132]
```csharp
    [BsonIgnoreExtraElements]
    public sealed class AccountInfo : ComponentWithId
    {
        public string account { get; set; } = null;
        public string nick_name { get; set; } = null;
        public string password { get; set; } = null;
        public decimal balance { get; set; } = 0m;

        public override string ToString()
        {
            return $"account : {this.account}, nick_name : {this.nick_name}, password : {this.password}, balance : {this.balance}";
        }
    }
```

使用AccountInfo进行如下查询的时候，会报错：
```csharp
        [Get("login")]
        public async ETTask<HttpResult> Login(string account, string password)
        {
            var db = Game.Scene.GetComponent<DBProxyComponent>();
            var info = await db.Query<AccountInfo>(s => s.account.Equals(account));

            return info.Count > 0? Ok("success", info[0]) : Error($"not find {account}");
        }
```

错误信息如下：
```
2019-05-07 03:03:15.7763 AllServer 0001 System.Exception: Rpc Error: ETModel.DBQueryJsonRequest ---> ETModel.RpcException: Error: 102001 Message: System.Exception: 查询数据库异常! AccountInfo { "account" : "abcd0001" } ---> System.InvalidOperationException: Can't compile a NewExpression with a constructor declared on an abstract class
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitNewExpression(Expression expr)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody(CompilerScope parent, Boolean inlined, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody()
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)
   at System.Linq.Expressions.Expression`1.Compile()
   at MongoDB.Bson.Serialization.BsonClassMap.GetCreator() in /home/kevin/rider-workspace/ET/Server/ThirdParty/MongoDBDriver/MongoDB.Bson/Serialization/BsonClassMap.cs:line 1264
   at MongoDB.Bson.Serialization.BsonClassMap.CreateInstance() in /home/kevin/rider-workspace/ET/Server/ThirdParty/MongoDBDriver/MongoDB.Bson/Serialization/BsonClassMap.cs:line 446
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.DeserializeClass(BsonDeserializationContext context) in /home/kevin/rider-workspace/ET/Server/ThirdParty/MongoDBDriver/MongoDB.Bson/Serialization/Serializers/BsonClassMapSerializer.cs:line 140
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args) in /home/kevin/rider-workspace/ET/Server/ThirdParty/MongoDBDriver/MongoDB.Bson/Serialization/Serializers/BsonClassMapSerializer.cs:line 100
   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize[TValue](IBsonSerializer`1 serializer, BsonDeserializationContext context) in /home/kevin/rider-workspace/ET/Server/ThirdParty/MongoDBDriver/MongoDB.Bson/Serialization/IBsonSerializerExtensions.cs:line 49
   at MongoDB.Driver.Core.Operations.CursorBatchDeserializationHelper.DeserializeBatch[TDocument](RawBsonArray batch, IBsonSerializer`1 documentSerializer, MessageEncoderSettings messageEncoderSettings) in /home/kevin/rider-workspace/ET/Server/ThirdParty/MongoDBDriver/MongoDB.Driver.Core/Core/Operations/CursorBatchDeserializationHelper.cs:line 59
   at MongoDB.Driver.Core.Operations.FindCommandOperation`1.CreateCursorBatch(BsonDocument commandResult) in /home/kevin/rider-workspace/ET/Server/ThirdParty/MongoDBDriver/MongoDB.Driver.Core/Core/Operations/FindCommandOperation.cs:line 483
   at MongoDB.Driver.Core.Operations.FindCommandOperation`1.CreateCursor(IChannelSourceHandle channelSource, BsonDocument commandResult) in /home/kevin/rider-workspace/ET/Server/ThirdParty/MongoDBDriver/MongoDB.Driver.Core/Core/Operations/FindCommandOperation.cs:line 460
   at MongoDB.Driver.Core.Operations.FindCommandOperation`1.ExecuteAsync(IReadBinding binding, CancellationToken cancellationToken) in /home/kevin/rider-workspace/ET/Server/ThirdParty/MongoDBDriver/MongoDB.Driver.Core/Core/Operations/FindCommandOperation.cs:line 525
   at MongoDB.Driver.Core.Operations.FindOperation`1.ExecuteAsync(IReadBinding binding, CancellationToken cancellationToken) in /home/kevin/rider-workspace/ET/Server/ThirdParty/MongoDBDriver/MongoDB.Driver.Core/Core/Operations/FindOperation.cs:line 442
   at MongoDB.Driver.OperationExecutor.ExecuteReadOperationAsync[TResult](IReadBinding binding, IReadOperation`1 operation, CancellationToken cancellationToken) in /home/kevin/rider-workspace/ET/Server/ThirdParty/MongoDBDriver/MongoDB.Driver/OperationExecutor.cs:line 39
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperationAsync[TResult](IClientSessionHandle session, IReadOperation`1 operation, ReadPreference readPreference, CancellationToken cancellationToken) in /home/kevin/rider-workspace/ET/Server/ThirdParty/MongoDBDriver/MongoDB.Driver/MongoCollectionImpl.cs:line 1055
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken) in /home/kevin/rider-workspace/ET/Server/ThirdParty/MongoDBDriver/MongoDB.Driver/MongoCollectionImpl.cs:line 1135
   at ETModel.DBQueryJsonTask.Run() in /home/kevin/rider-workspace/ET/Server/Model/Module/DB/DBQueryJsonTask.cs:line 33
```

请问这个该如何解决？

**Comment by zhuxian** [comment]
打开`Server\Hotfix\Module\Http`中的`HttpTest.cs`的如下脚本，调用也会报相同类型的错：
```csharp
		[Get] // url-> /GetRechargeRecord
		public async ETTask<HttpResult> GetRechargeRecord(long id)
		{
			var db = Game.Scene.GetComponent<DBProxyComponent>();

			var info = await db.Query<RechargeRecord>(id);

			//await Task.Delay(1000); // 用于测试

			//object info = null;
			if (info != null)
			{
				return Ok(data: info);
			}
			else
			{
				return Error("ID不存在！");
			}
		}
```

**Comment by zhuxian** [comment]
找到问题了。
错误是因为我没有按照格式注入数据库，我才用的错误的注入方式：
```csharp
        public async Task AddTestAccountInfo10()
        {
            var database = this.Initialization();
            var collection = database.GetCollection<AccountInfo>(typeof(AccountInfo).Name);
            List<AccountInfo> infos = new List<AccountInfo>();
            for (int i = 0; i < 10; i++)
            {
                AccountInfo account = new AccountInfo();
                account.Account = "abcd" + string.Format("{0:D4}", i + 1);
                account.NickName = "abcd" + string.Format("{0:D4}", i + 1);
                account.Password = "123456";
                account.Balance = 0;

                infos.Add(account);
            }
            await collection.InsertManyAsync(infos);
            Console.WriteLine("add success");
        }
```

而正确的注入方式应该是：
```csharp
        public async ETTask<HttpResult> Register(string account, string password) {
            AccountInfo info = ComponentFactory.CreateWithId<AccountInfo>(IdGenerater.GenerateId());
            info.Account = account;
            info.Password = password;

            var db = Game.Scene.GetComponent<DBProxyComponent>();
            await db.Save(info);

            return this.Ok("success");
        }
```
