### ISSUE TITLE
5.0分支 升级协程锁后 demo进入地图失败

### ISSUE THREAD

**Issue by shimaoye** [egametang/ET#211]
<G2C_EnterMap>{RpcId:1, Error:102001, Message:"System.Exception: Rpc Error: ETModel.G2M_CreateUnit 102001
   at ETModel.ETTaskCompletionSource`1.ETModel.IAwaiter<T>.GetResult() in G:\GamePower\et-mmo\Unity\Assets\Model\Base\Async\ETTaskCompletionSource.cs:line 171
   at ETModel.ETTask`1.get_Result() in G:\GamePower\et-mmo\Unity\Assets\Model\Base\Async\ETTask.cs:line 168
   at ETModel.ETTask`1.Awaiter.GetResult() in G:\GamePower\et-mmo\Unity\Assets\Model\Base\Async\ETTask.cs:line 254
   at ETHotfix.C2G_EnterMapHandler.Run(Session session, C2G_EnterMap request, G2C_EnterMap response, Action reply) in G:\GamePower\et-mmo\Server\Hotfix\Module\Demo\C2G_EnterMapHandler.cs:line 16
   at ETModel.ETTaskCompletionSource.ETModel.IAwaiter.GetResult() in G:\GamePower\et-mmo\Unity\Assets\Model\Base\Async\ETTaskCompletionSource.cs:line 32
   at ETModel.ETTask.GetResult() in G:\GamePower\et-mmo\Unity\Assets\Model\Base\Async\ETTask.cs:line 33
   at ETModel.ETTask.Awaiter.GetResult() in G:\GamePower\et-mmo\Unity\Assets\Model\Base\Async\ETTask.cs:line 98
   at ETModel.AMRpcHandler`2.Handle(Session session, Object message) in G:\GamePower\et-mmo\Server\Model\Module\Message\AMRpcHandler.cs:line 37", UnitId:0, Units:[]}
UnityEngine.Debug:Log(Object)
ETModel.Log:Debug(String) (at Assets/Model/Base/Log.cs:14)
ETModel.Log:Msg(Object) (at Assets/Model/Base/Log.cs:74)
ETModel.Session:Run(MemoryStream) (at Assets/Model/Module/Message/Session.cs:150)
ETModel.Session:OnRead(MemoryStream) (at Assets/Model/Module/Message/Session.cs:120)
ETModel.AChannel:OnRead(MemoryStream) (at Assets/Model/Module/Message/Network/AChannel.cs:55)
ETModel.TChannel:OnRecvComplete(Object) (at Assets/Model/Module/Message/Network/TCP/TChannel.cs:279)
ETModel.<>c__DisplayClass7_0:<Post>b__0() (at Assets/Model/Base/OneThreadSynchronizationContext.cs:38)
ETModel.OneThreadSynchronizationContext:Update() (at Assets/Model/Base/OneThreadSynchronizationContext.cs:26)
ETModel.Init:Update() (at Assets/Model/Init.cs:55)

**Comment by dingwenjie** [comment]
好像不升级这个协程锁提交，启动server用127.0.0.1.txt 这个配置，也是报这个错，但是不升级协程锁的时候，用localallserver.txt 这个配置是没问题的

**Comment by egametang** [comment]
应该已经修复了，我测试过

**Comment by dingwenjie** [comment]
环境：
win10, 
vs2019, 
unity 2018.4.9f1, 
ET Branch_V5.0, 
b6dcc4d8db7080b5c7acd4318178bba68e73a023 commit

大佬，用 “更新使用6.0的协程锁，解决锁冲突的问题” 这次提交下的代码测试，在使用127.0.0.1.txt 这个配置启动多个进程的时候，还是会遇到这个同样的错误，但是用LocalAllServer.txt的时候，就可以正常进去。@egametang

**Comment by egametang** [comment]
已修复
