### ISSUE TITLE
请问：使用Protobuf序列化数据爆出一下面的错误

### ISSUE THREAD

**Issue by MrTigerZhang** [egametang/ET#26]
2017-11-29 16:48:14.9084 AllServer 001 (Session.cs:109) message deserialize error, ip: 127.0.0.1:57087 119 ProtoBuf.ProtoException: No parameterless constructor found for Model.ARequest
   at ProtoBuf.Meta.TypeModel.ThrowCannotCreateInstance(Type type) in C:\code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs:line 1462
   at proto_10(Object , ProtoReader )
   at ProtoBuf.Meta.TypeModel.DeserializeCore(ProtoReader reader, Type type, Object value, Boolean noAutoCreate)
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context)
   at ProtoBuf.Serializer.NonGeneric.Deserialize(Type type, Stream source)
   at Model.ProtobufHelper.FromBytes(Type type, Byte[] bytes, Int32 index, Int32 length)
   at Model.ProtobufPacker.DeserializeFrom(Type type, Byte[] bytes, Int32 index, Int32 count)
   at Model.Session.RunDecompressedBytes(UInt16 opcode, Byte[] messageBytes, Int32 offset) Program.Main => OneThreadSynchronizationContext.Update => <>c__DisplayClass3_0.<Post>b__0 => ExecutionContext.Run => <StartRecv>d__15.MoveNext => TaskCompletionSource`1.SetResult => TaskCompletionSource`1.TrySetResult => Task`1.TrySetResult => Task.RunContinuations => AwaitTaskContinuation.RunCallback => ExecutionContext.Run => <StartRecv>d__13.MoveNext => Session.Run => Session.RunDecompressedBytes => Log.Error => NLogAdapter.Error

**Comment by MrTigerZhang** [comment]
enmmmmmmm. 客户端和服务端。相互调用的两端直接的packer要保持一致。
