### ISSUE TITLE
导表float类型报错

### ISSUE THREAD

**Issue by rekcah1986** [egametang/ET#274]
![7C9DC8EF-6E05-4F31-8505-9F2DA380A94D](https://user-images.githubusercontent.com/3055444/139620948-0d655171-9000-46af-99a3-2b2bf44ff947.png)

```
/usr/local/share/dotnet/dotnet /Users/xxx/Documents/ET/Tools/ExcelExporter/Bin/ExcelExporter.dll
System.FormatException: An error occurred while deserializing the list field of class ET.UnitConfigCategory: An error occurred while deserializing the Speed property of class ET.UnitConfig: Truncation resulted in data loss.
 ---> System.FormatException: An error occurred while deserializing the Speed property of class ET.UnitConfig: Truncation resulted in data loss.
 ---> MongoDB.Bson.TruncationException: Truncation resulted in data loss.
   at MongoDB.Bson.Serialization.Options.RepresentationConverter.ToSingle(Double value)
   at MongoDB.Bson.Serialization.Serializers.SingleSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.Serializers.SerializerBase`1.MongoDB.Bson.Serialization.IBsonSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize(IBsonSerializer serializer, BsonDeserializationContext context)
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.DeserializeMemberValue(BsonDeserializationContext context, BsonMemberMap memberMap)
   --- End of inner exception stack trace ---
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.DeserializeMemberValue(BsonDeserializationContext context, BsonMemberMap memberMap)
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.DeserializeClass(BsonDeserializationContext context)
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize[TValue](IBsonSerializer`1 serializer, BsonDeserializationContext context)
   at MongoDB.Bson.Serialization.Serializers.EnumerableSerializerBase`2.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.Serializers.SerializerBase`1.MongoDB.Bson.Serialization.IBsonSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize(IBsonSerializer serializer, BsonDeserializationContext context)
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.DeserializeMemberValue(BsonDeserializationContext context, BsonMemberMap memberMap)
   --- End of inner exception stack trace ---
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.DeserializeMemberValue(BsonDeserializationContext context, BsonMemberMap memberMap)
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.DeserializeClass(BsonDeserializationContext context)
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.Serializers.SerializerBase`1.MongoDB.Bson.Serialization.IBsonSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize(IBsonSerializer serializer, BsonDeserializationContext context)
   at MongoDB.Bson.Serialization.BsonSerializer.Deserialize(IBsonReader bsonReader, Type nominalType, Action`1 configurator)
   at MongoDB.Bson.Serialization.BsonSerializer.Deserialize(String json, Type nominalType, Action`1 configurator)
   at ET.Program.ExportExcelProtobuf(ConfigType configType) in /Users/xxx/Documents/ET/Tools/ExcelExporter/Program.cs:line 339
   at ET.Program.Main(String[] args) in /Users/xxx/Documents/ET/Tools/ExcelExporter/Program.cs:line 91
```

**Comment by rekcah1986** [comment]
填3.2报错，3.25就不报错，好像是Bson的问题

**Comment by rekcah1986** [comment]
Main里加了行代码
BsonSerializer.RegisterSerializer(typeof(float), new SingleSerializer(BsonType.Double, new RepresentationConverter(true, true)));
