### ISSUE TITLE
StartMachineConfig配置的OuterIP字段填写外网IP报错

### ISSUE THREAD

**Issue by lamatimo** [egametang/ET#345]
StartMachineConfig配置的OuterIP字段填写外网IP报错

填写内网IP没事

**Comment by egametang** [comment]
云的外网IP不是在物理机上，所以bind不了，所以如果在云上部署，StartMachineConfig中仍然填外网地址，但是代码中需要绑定内网地址 scene.AddComponent<NetKcpComponent, IPEndPoint, int>(startSceneConfig.OuterIPPort
这里把startSceneConfig.OuterIPPort 改成 startSceneConfig.InnerIPPort 即可，
注意realm跟gate都需要改。然后在防火墙中把端口映射到这个内网端口即可

**Comment by lamatimo** [comment]
ok 谢谢熊猫大大

**Comment by liyuping6666** [comment]
ET7.0 腾讯云linux服务器怎么部署，请指导一下。公网ip socket绑定就报错，内网ip不报错但是无法连接
2022-07-12 16:30:40.2542  System.Net.Sockets.SocketException (99): Cannot assign requested address
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at ET.RouterComponentSystem.RouterComponentAwakeSystem.Awake(RouterComponent self, IPEndPoint outerAddress, String innerIP) in E:\Unity\ET\Apps\Hotfix\Module\Router\RouterComponentSystem.cs:line 19

楼上说的防火墙中把端口映射到这个内网端口，请问一下腾讯云哪个地方可以设置
