### ISSUE TITLE
TimerComponent在WaitAsync时可能会报异常导致无限写日志

### ISSUE THREAD

**Issue by Viagi** [egametang/ET#39]
2018-01-20 18:00:00.0128 AllServer 001 (ObjectEvents.cs:265) System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Model.TimerComponent.Update() in E:\WesternMini2017\ETFramework\trunk\Unity\Assets\Scripts\Component\TimerComponent.cs:line 49
   at Model.TimerComponentEvent.Update() in E:\WesternMini2017\ETFramework\trunk\Unity\Assets\Scripts\Component\TimerComponent.cs:line 19
   at Model.ObjectEvents.Update() in E:\WesternMini2017\ETFramework\trunk\Server\Model\Base\Object\ObjectEvents.cs:line 265

**Comment by egametang** [comment]
好的，3q，我大概知道是什么问题了

**Comment by egametang** [comment]
已修复
